- name: install requirements
  apt: name=python-psycopg2 state=present
  become: yes

- name: add users
  postgresql_user: name={{ item.name }} role_attr_flags=SUPERUSER
  with_items:
    - { name: pqsql }
    - { name: insales }
  become: yes
  become_user: postgres
