- name: update pakages
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: install java
  apt: name={{ es_java_version }} state=present
  become: yes
  when: es_install_java

- name: adding gpg key
  apt_key: url={{ es_repositoty_key }} state=present
  become: yes

- name: add repository
  apt_repository: repo={{ es_repositoty }} state=present
  become: yes

- name: install
  apt: name=elasticsearch state=present
  become: yes

- name: check installed plugins
  shell: bin/plugin -l chdir={{ es_dir }}
  changed_when: false
  register: es_installed_plugins

- name: instal plugins
  shell: bin/plugin -install {{ item.name }} -url {{ item.url }} chdir={{ es_dir }}
  become: yes
  with_items:
    - {
        name: "analysis-morphology",
        url: "http://dl.bintray.com/content/imotov/elasticsearch-plugins/org/elasticsearch/elasticsearch-analysis-morphology/1.2.0/elasticsearch-analysis-morphology-1.2.0.zip"
      }
  when: "'- {{item.name}}' not in es_installed_plugins.stdout"

- name: start service
  service: name=elasticsearch state=restarted enabled=yes
  become: yes
